### ISSUE TITLE
Upgrade to Turbo 2.0

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#103]
### Description

Turbo v2.0 is out and we should upgrade to it.

### Use Case

We should be using the latest available version of software packages whenever possible.

**Comment by goodguyry** [comment]
What's New
https://turbo.build/blog/turbo-2-0

Breaking Changes
https://turbo.build/blog/turbo-2-0#breaking-changes

Upgrade Guide
https://turbo.build/repo/docs/crafting-your-repository/upgrading#upgrading-to-20
