### ISSUE TITLE
Unprosecuted larceny

### ISSUE THREAD

**Issue by szepeviktor** [alleyinteractive/create-wordpress-project#16]
### Description

Hello @kevinfodness! 👋🏻 
You may steal as much as you want!
https://github.com/szepeviktor/composer-managed-wordpress

<details><summary>🎁</summary>

And there is a higher level one: https://github.com/szepeviktor/wordpress-website-lifecycle

</details>

### Use Case

_none_

**Comment by kevinfodness** [comment]
Thanks, but this is for managed hosting providers like WordPress VIP and Pantheon who manage WordPress and related software for us at the platform level, and we are just responsible for developing custom themes and installing third party plugins (which we already manage via Composer) as well as developing our own custom plugins. That's a great solution for a different use case than ours.

**Comment by szepeviktor** [comment]
All right.
These providers go for the money. They never care about a project as their own child 👶🏻
