### ISSUE TITLE
Setup Slack Notifications for Deployment Failures

### ISSUE THREAD

**Issue by srtfisher** [alleyinteractive/create-wordpress-project#38]
### Description

I would like to be able to know from Slack that a deployment has failed.

### Use Case

When a user's deployment action fails we should be able to be alerted in Alley Slack preferably with Alleybot.

**Comment by benpbolton** [comment]
I've been pondering about this a bit... I think the simple-stick approach would be to create a new webhook listener (caught by alleybot) ... then set an org-wide webhook for 'check runs' and 'check suites' (I *think* that would give us half the proper context)... then leverage alleybot commands to 'listen for repo ____' or something that would associate the hook with the channel... so hooks come in, we parse them for appropriate data, and any subscribed channels get a notification.

seems likely to result in less work/mistakes with an org-wide webhook (vs. a reusable action or workflow that peeps would need to remember to add.... to... every. action....?) 

thoughts on approach?

**Comment by srtfisher** [comment]
I think that approach would work well to give us the flexibility to change it as needed and without the risk of sharing anything made-for-internal with the public world.

**Comment by benpbolton** [comment]
@srtfisher are we happy with the implementation now via listen via `@alleybot add repo owner/repo` ?

**Comment by srtfisher** [comment]
I think we're good here!
