### ISSUE TITLE
Add Buddy Branch Sync Configuration for Pantheon

### ISSUE THREAD

**Issue by benpbolton** [alleyinteractive/create-wordpress-project#45]
### Description

Add a Buddy pipeline that will enable automatic sync of branches from one repository (on alley) to another (pantheon) on push. For example, upon pushing to branch `xyz` on this repo, it will automatically sync that change to branch `xyz` on the pantheon repo. Primary use case is for Pantheon deployments, in which changes are sync'd to the pantheon repo on push to specified branches such as `develop`, `preprod`, `production`, etc.

### Use Case

When a user uses this repo to manage their Pantheo site, they should be able to sync changes from a version of the repo in their own organization to Pantheon. 

### Extra context/warnings:

- Notably, it should also copy the `pantheon.yml` files to the root of the repository. See [this example we've done leveraging github actions](https://github.com/alleyinteractive/action-deploy-to-remote-repository/blob/develop/deploy-to-remote-repository.sh) for that approach. 
- Pantheon doesn't have `develop` or `preprod` environments (they have a dev -> test -> live workflow with auto-promotion, you'll need to handle that for the production case in something like this github actions approach:

```
deploy-to-pantheon:
    runs-on: ubuntu-latest
    needs: build-and-sync
    steps:
    - name: Install PHP
      run: sudo apt-get install php

    - name: Install Terminus
      run: |
        mkdir -p /tmp/terminus && cd /tmp/terminus
        curl -L https://github.com/pantheon-systems/terminus/releases/download/${{ env.TERMINUS_VERSION }}/terminus.phar --output terminus
        chmod +x terminus
        ./terminus self:update
        sudo mv /tmp/terminus/terminus /usr/local/bin/terminus

    - name: Authenticate with Terminus
      run: terminus auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Deploy to Test
      run: |
        terminus env:deploy ${{ env.PANTHEON_SITE }}.test --note="Deploying ${{ github.event.head_commit.message }} from GitHub Actions"
        terminus env:clear-cache ${{ env.PANTHEON_SITE }}.test

    - name: Deploy to Live
      run: |
        terminus env:deploy ${{ env.PANTHEON_SITE }}.live --note="Deploying ${{ github.event.head_commit.message }} from GitHub Actions"
        terminus env:clear-cache ${{ env.PANTHEON_SITE }}.live
```

... so that terminus is auto-promoting dev -> test -> live. 

- You'll also want to notify terminus that you have deployed to one of the multisite environments (to trigger the quicksilver scripts) like:
```
          terminus env:deploy ${{ env.PANTHEON_SITE }}.${{ github.ref_name }} --note="Deploying ${{ github.event.head_commit.message }} from GitHub Actions"
```

### Acceptance Criteria

- Create the `.ci-templates/.buddy` folder, if it doesn't already exist
- Deploy pipeline exists for the `production` (dev -> test -> live) workflow and another for the mutisites (`preprod`, and `develop` ) ... they should all trigger the appropriate terminus env:deploy post-deploy triggers

### Bonus Points

- Consolidate the pipelines as much as reasonable one, since most of the code is shared; make the pipeline respond to pushes to `production`, `preprod`, and `develop` and make the branch name part dynamic. One area that may be tricky here is the priority, which may not be able to be negotiated based on branch name.

**Comment by kevinfodness** [comment]
Not going to do this because we're consolidating on GitHub Actions.
