### ISSUE TITLE
Install Recommended Plugins as Part of Install

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#47]
### Description

I would like to be prompted when running the installer script to install recommended plugins. If I say yes, I want the recommended plugins to be added to composer.json and installed at their latest versions.

Can use the [suggest property in Composer](https://getcomposer.org/doc/04-schema.md#suggest) to suggest installation of certain things under certain circumstances.

### Default Required Plugin List
- [Alleyvate](https://github.com/alleyinteractive/wp-alleyvate)
- [Byline Manager](https://github.com/alleyinteractive/byline-manager)
- [Elasticsearch Extensions](https://github.com/alleyinteractive/elasticsearch-extensions)
- [Meta Inspector](https://github.com/alleyinteractive/meta-inspector)
- [MSM Sitemap](https://github.com/Automattic/msm-sitemap)
- [Safe Redirect Manager](https://wordpress.org/plugins/safe-redirect-manager/)
- [WP Asset Manager](https://github.com/alleyinteractive/wp-asset-manager)
- [WP Curate](https://github.com/alleyinteractive/wp-curate)
- [WP New Relic Transactions](https://github.com/alleyinteractive/wp-new-relic-transactions)
- [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/)

### Suggested Plugins
- [ES Admin](https://github.com/alleyinteractive/es-admin)
- [ES WP Query](https://github.com/alleyinteractive/es-wp-query)
- [Fieldmanager](https://github.com/alleyinteractive/wordpress-fieldmanager)
- [Yoast Duplicate Post](https://wordpress.org/plugins/duplicate-post/)

### Install Automatically if Pantheon
- [Pantheon Advanced Page Cache](https://github.com/pantheon-systems/pantheon-advanced-page-cache)
- [Pantheon MU Plugin](https://github.com/pantheon-systems/pantheon-mu-plugin)
- [Query Monitor](https://wordpress.org/plugins/query-monitor/)
- [Rewrite Rules Inspector](https://wordpress.org/plugins/rewrite-rules-inspector/)
- [SearchPress](https://github.com/alleyinteractive/searchpress)
- [SearchPress Debug Bar](https://github.com/alleyinteractive/debug-bar-searchpress)
- [Two Factor](https://wordpress.org/plugins/two-factor/)
- [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/)
- [WP Native PHP Sessions](https://wordpress.org/plugins/wp-native-php-sessions/)

For Pantheon, need to install Object Cache Pro, but requires a token to do so via Composer: https://objectcache.pro/docs/composer-installation

### Use Case

As a developer, I want to be able to easily install Alley's recommended list of plugins when creating a new site.

**Comment by srtfisher** [comment]
Proposed plugins:

- https://github.com/alleyinteractive/meta-inspector
- https://github.com/alleyinteractive/wp-alleyvate
