### ISSUE TITLE
Create Primary Category Custom Block

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#53]
### Description

There should be a way to insert a primary category (e.g., an eyebrow) into post templates using full site editing. The core blocks only support a category list with no way to restrict to just one category.

### Use Case

> As an editor, I want to be able to set a primary category and have it appear above the post title.

### Acceptance Criteria

- Create a custom block for primary category.
- If Yoast SEO is installed, ensure the primary category selection controls which category is used. Otherwise, just use the first selected category in the list.

### Technical Details

- This will use the plugin templates system defined in #51 
- Place the block in `plugin-templates/blocks/theme-primary-category`
- Ensure the namespace is `create-wordpress-plugin` so find and replace works properly
- Test with Yoast SEO's primary category feature enabled and without
- Ensure the category of the block is set to `theme`

**Comment by kaitlinbolling** [comment]
It could be a nice enhancement to make the `category` taxonomy filterable. Or, maybe even better, write a block with a taxonomy attribute and use block style variations for all registered taxonomies. It looks like this is what core does with the [core/post-terms block](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-terms/index.php#L61-L109).

That block also has attributes for a `suffix` and `prefix`.
