### ISSUE TITLE
Create Pull Request Roll-Up Task

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#63]
### Description

Currently, the PR checks are all separate tasks, which can contain different configuration options like PHP and node versions, could contain matrices, etc. When changing the configuration of these jobs, their names change, and then branch protection rules need to be updated to reflect the new names/versions/etc. Instead, it would be ideal to have an immutable name that could be set for a workflow and required, and the implementation details of that workflow could be changed as needed without needing to change the branch protection rules.

ref: https://stackoverflow.com/questions/70275958/how-do-i-set-a-github-branch-protection-rule-based-on-the-success-or-failure-of/75250293#75250293

### Use Case

> As a developer, I want to be able to change the configuration values for a workflow, such as PHP and node version, without requiring an admin to change the branch protection rules.

### Acceptance Criteria

- Ensure GitHub Actions workflows have an immutable name that does not change when configuration values such as PHP or node versions change.
- Group workflows by type (e.g., PHP tests, node tests) but several related workflows could be executed in the same workflow (e.g., phpcs + phpstan + phpunit).
- Ensure that a failure in any one of the steps in a workflow causes the entire workflow to report failure.
- Ensure that the individual workflow items (e.g., running phpunit on PHP 8.2 with multisite) show up as individual checks in GitHub Actions, they just aren't marked as required, only the rollup task is. If this is not possible, and check results are "hidden" behind a single rollup task where failure information is hard to glean, then we should abandon this approach.

**Comment by srtfisher** [comment]
This worked really well for NYP.
