### ISSUE TITLE
Add Installer Script

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#7]
# User Story

> As a developer, I want to be able to initialize a new project based on create-wordpress-project by running a script and answering questions, which results in preconfiguration of the repo based on my preferences.

# Acceptance Criteria

- Add an installer script similar to the one used on [create-wordpress-plugin](https://github.com/alleyinteractive/create-wordpress-plugin) which asks the user questions, such as whether this project will be run on VIP or Pantheon, what the project namespace and name should be, who the author is, and then performs an automated installation that will:
  - Perform an automatic installation of [create-wordpress-plugin](https://github.com/alleyinteractive/create-wordpress-plugin) without the need for further user input (all option values pre-configured), error out if the chosen directory name already exists
  - Perform an automatic installation of `create-wordpress-theme`, error out if the chosen directory name already exists
  - Run a find-replace for strings relating to `create-wordpress-project`, `create-wordpress-plugin`, `create-wordpress-theme` and update them as necessary
  - Run `composer setup` to install PHP and JS dependencies and run an initial build
  - Ask about what CI systems are being used and only preserve files necessary for those CI systems (GitHub Actions vs. Buddy, taking into account the chosen hosting platform, e.g., if Pantheon and GitHub Actions, include autodeploy action for Pantheon)
  - Clean up after itself (delete CI config files that aren't part of what was requested to be preserved, remove the installer script itself)

**Comment by benpbolton** [comment]
See related: #23
