### ISSUE TITLE
Fix slack notifications in the buddy deploy to vip yaml file

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/create-wordpress-project#78]
### Description

When we created the Buddy deploy to VIP yaml file, we tried to use a Workspace Variable so we wouldn't have to put our slack_integration_hash in the public repository. This does not actually work, and the yaml file does not validate. I talked with Buddy support and they said:

integration_hash doesn't support resolving variables during pipeline run.
The good news is that we have just merged a new way to reference integrations.
![CleanShot 2024-03-07 at 16 11 20@2x](https://github.com/alleyinteractive/create-wordpress-project/assets/11542164/1f4dd224-c569-4986-a793-fffaae5f0a5d)

instead of integration_hash you will use ID in YAML
in this case it will be: wWMAoVqQK9b6zEqQbEvYnGpx8j
![CleanShot 2024-03-07 at 16 14 47@2x](https://github.com/alleyinteractive/create-wordpress-project/assets/11542164/bf08d618-ca0c-44c8-89c4-0a247231eb2f)

the ID also can have a variable as value and it will be resolved on pipeline run

it will ship on 12th March

with the introduction of the ID you won't need to create a variable with the hash for an integration, it will be automatically created for you so you can reference it anywhere you want.

### Use Case

buddy deploy script can notify slack without needing the integration_hash in plain text.

**Comment by kevinfodness** [comment]
Consolidating on GitHub Actions.
