### ISSUE TITLE
Add JS Structure

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#8]
### Description

Create a structure for managing JS dependencies and tooling that meets the following criteria:
- Must be installed at the root so we only need to run `npm ci` once, rather than in one or more plugin and theme directories
- Dependency versions are centrally managed (e.g., all custom code in the repo uses the same version of a package and the same version of node, rather than possibly using different versions per-directory)
- Must have a way to run builds on plugins and themes
- Must externalize dependencies to the extent possible via [alley-scripts](https://github.com/alleyinteractive/alley-scripts) so the build system/linting system/test system/etc can be updated as an external dependency rather than reconfigured here
- Must support TypeScript
- Must support block-building system used in the plugin
- Should be as close to zero-configuration as possible - implementers should be able to create files in plugins and themes, they should be picked up and used automatically
- Must use the Dependency Extraction Webpack Plugin so that any packages that are externalizable to WordPress bundled scripts and globals are used rather than bundling packages into output directly (e.g., React, ReactDOM, i18n, etc, for both front-end and back-end scripts)

### Use Case

When a user uses this repository to manage a project, they should be able to install JS dependencies, run builds, linting, and tests using npm in a performant and scalable way.

**Comment by kevinfodness** [comment]
One suggestion was to use [TurboRepo](https://turbo.build/repo/docs) for this, which would allow us to have a common set of dependencies among several subfolders, each with their own package.json, build and linting steps, and so on. An advantage of this approach is that it lets us consolidate dependencies in practice while being able to use the existing package.json in create-wordpress-plugin, for example, and eventually create-wordpress-theme.

However, using Turbo means that there are some additional overhead steps, like needing to add packages to subfolders by specifying a workspace, and needing to ensure that versions of packages are the same between folders (Turbo actually supports multiple versions of dependencies per folder, but we explicitly don't want that, so we'd need to be responsible for ensuring that when we upgrade we're upgrading in all places and confirming versions are the same).

Turbo was designed for use as a monorepo where multiple packages or products can be published from one common repo, which is great for publishing packages to npm, or publishing a backend and a frontend out of a single, unified repo. However, in the case of this repo, we're just building files for _n_ plugins and _n_ themes, where _n_ is `>= 1`. I think we would benefit from having all dependencies defined at the root (devdependencies and regular) and then set up a build and linting config that will run builds on plugins and themes, will lint plugins and themes, and the like from a central place.

We're already doing a version of this with the different entry points we define in Webpack. What I'm proposing here is that instead of locating that webpack/build configuration at the plugin level and at the theme level, we hoist it to `wp-content` and load entries from subfolders that happen to be in the plugins directory and the themes directory.

**Comment by stevenslack** [comment]
An important thing to note here is that when you declare an NPM workspace with a package.json file you do not have to declare the dependency in the subfolder package.json unless you want a different version for that plugin/themes specific needs. Otherwise it will use the shared dependency from the root.

If the project upgrading method doesn't have different versions in subfolders this will be a pretty seamless pathway. Alternatively if there are exceptions running `npm outdated` in the root will show what versions are not in sync with the root `node_modules` and on different versions. But upgrading in those respective subfolders would not be any different than what we are doing now in a non-workspace environment.

I think that if we had a build script that was called from the relative working directory (subfolder) or from the root (turbo w/ NPM workspace) we could have the workspace build script transpile / compile the assets relative to that subfolder. The key here is having that config called from the current working directory, but the config itself can live in the root where each workspace can (optionally) have a config for plugin/theme specific overrides where necessary while still having all the dependencies defined at the root.

**Comment by stevenslack** [comment]
The challenge for developers maintaining packages could be alleviated with proper documentation on an upgrading/updating pathway. If we extract the build to an `alley-scripts` package then updating those dependencies will remain in the hands of the maintainers there. In which case we could use dependabot to update patches and minor versions to npm.

**Comment by kevinfodness** [comment]
Take a look at what I did in https://github.com/alleyinteractive/create-wordpress-project/pull/24 and let me know what you think. I was going for a config that would work from the root but would be simple to maintain. What would be the advantages of adding Turbo to this structure?

**Comment by kevinfodness** [comment]
I merged my PR for the initial JS structure, which closed this issue, but if we decide we want to layer in Turbo at a later date we can, so let's keep the conversation going about whether that's a direction we want to go in or not.

**Comment by stevenslack** [comment]
@kevinfodness 
> I was going for a config that would work from the root but would be simple to maintain. What would be the advantages of adding Turbo to this structure?

I think of this question more of a question of whether or not to use a monorepo with [NPM workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces?v=true). 

From Turborepo's docs:
> Turborepo is an intelligent build system optimized for JavaScript and TypeScript codebases.
Your codebase's tasks - like lint, build and test - don't run as fast as they could. Turborepo uses [caching](https://turbo.build/repo/docs/core-concepts/caching) to turbocharge your local setup and speed up your CI. 
Turborepo is designed to be incrementally adopted, so you can add it to most codebases in a few minutes.

Simply put, it acts as the icing on the NPM workspaces cake. 🎂

That being said, the pattern we are aiming to achieve in #24 is where:
- Dependency versions are centrally managed,
- Dependencies are installed at the root wp-content directory,
- It should provide a method to execute builds on plugins and themes,
- And it should be simple to maintain.

**All of these aspects point towards the advantage of using a monorepo with turbo**. Furthermore, building files in each respective plugin and theme can be easily setup with NPM workspaces with Turbo to where the developer has the option of working in the plugin or theme directory OR running those commands from the root as well. All while leveraging the same shared dependencies.

If you intend to create a build command from the root, similar to the referenced command in #24, you can simply utilize the Turbo command: `turbo run build --cache-dir=./.cache --parallel`. This approach eliminates the need to add individual build scripts such as `"npm run build:plugin && npm run build:theme"`. By leveraging Turbo, you can streamline the process and execute the build command efficiently and concurrently, leading to improved performance. This principle extends to other commonly used scripts as well. Turbo enables these commands to run exceptionally fast, providing the advantage of executing a single command for the entire codebase, whether it's for builds, linting, or tests. This streamlined approach proves to be highly advantageous for CI/CD processes, allowing for efficient and swift execution of various tasks across the codebase.

**Comment by kevinfodness** [comment]
Thanks, that's helpful. I'll create a new issue specific to implementing npm workspaces/turbo and link this one to it where we can continue the discussion.

**Comment by kevinfodness** [comment]
Discussion of npm workspaces / turbo moved to #27
