### ISSUE TITLE
Fix PHPStan Paths for WordPress VIP

### ISSUE THREAD

**Issue by efuller** [alleyinteractive/create-wordpress-project#97]
### Description of the bug

If a site is selected to be hosted on VIP, the PHPStan paths are pointing to `mu-plugins/` and they need to be pointed to `client-mu-plugins`

Perhaps we could add a step to the config to allow for renaming to take place based on whether the site will be hosted on VIP or not.

### Steps To Reproduce

1. Run `make` command
2. Be sure to configure site to be hosted on VIP
3. Try running PHPStan

**Comment by mslinnea** [comment]
Hi @efuller 

Does this look to fix the issue? https://github.com/alleyinteractive/create-wordpress-project/pull/115

@kevinfodness @dlh01 Do you have any feedback here?  

Is there any way to test this fully aside from creating a test repo using this project as a template?

**Comment by dlh01** [comment]
I don't think I have any useful feedback to offer except to say that I recall only running the configure script locally to test changes that I made, not going through the full process of creating a repo, for better or worse.

**Comment by kevinfodness** [comment]
Agreed, it's not necessary to create a new repo using this one as a template. Running the configure script locally is a perfectly acceptable way to test. If you'd like, you can copy the files into a separate folder locally, run the configure script, then make changes as necessary to satisfy PHPStan in the source directory, then delete the copied directory where you ran configure, make a fresh copy and run configure and PHPStan to confirm your solution worked, then ship it.

**Comment by mslinnea** [comment]
Thanks! I followed these steps, created a VIP project, ran PHPStan with my changes here, and all passed :)
